{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "PowerPulse",
    "description": "PowerPulse backend"
  },
  "servers": [
    {
      "url": "https://powerpulse-y0gd.onrender.com/api"
    },
    {
      "url": "http://localhost:3000/api"
    }
  ],
  "tags": [
    {
      "name": "Dashboard",
      "description": "General information"
    },
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Users",
      "description": "Users endpoints"
    },
    {
      "name": "Products",
      "description": "Products endpoints"
    },
    {
      "name": "Exercises",
      "description": "Exercises endpoints"
    },
    {
      "name": "Diary",
      "description": "Diary endpoints"
    }
  ],
  "paths": {
    "/dashboard": {
      "get": {
        "tags": [
          "Dashboard"
        ],
        "summary": "Get general information from application",        
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DashboardResponse"
                }
              }
            }
          },          
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/signup": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "User sign up",
        "requestBody": {
          "description": "Sign up object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignUpRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SignUpResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "409": {
            "description": "Such email already exists",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/signin": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "User sign in",
        "requestBody": {
          "description": "Sign in object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignInRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SignInResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Email or password invalid",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Get current user info",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetCurrentResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/signout": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "User sign out",
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SignOutResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/body": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Add user body data info",
        "security": [
          {
            "Bearer": []
          }
        ],
        "requestBody": {
          "description": "Add user body data object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddBodyRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddBodyResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/current/edit": {
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "User update",
        "security": [
          {
            "Bearer": []
          }
        ],
        "requestBody": {
          "description": "Update object",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "User name",
                    "type": "string",
                    "format": "json",
                    "example": "UserName"
                  },
                  "avatar": {
                    "description": "File to upload",
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserUpdateResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },    
    "/products": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get information for products category",        
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductsCategoryResponse"
                }
              }
            }
          },          
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/products/admissible": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get information for products list",        
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductsListResponse"
                }
              }
            }
          },          
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
     "/products/admissible/?filter=false": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get information about the list of products filtered with the permission of the blood group",        
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductsListFilteredBloodResponse"
                }
              }
            }
          },          
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/products/admissible/?category=*": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get information about the list of products filtered by category group",        
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductsListFilteredCategoryResponse"
                }
              }
            }
          },          
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/products/admissible/?page=1&limit=5": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get information about pagination of products list",        
        "responses": {
          "200": {
            "description": "Successful operation"
           
          },          
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "DashboardResponse": {
        "type": "object",
        "properties": {
          "totalVideoTrainings": {
            "type": "integer"
          },
          "totalBurnedCalories": {
            "type": "integer"
          },
          "totalUsers": {
            "type": "integer"
          },
          "totalTrainingTime": {
            "type": "string"
          },
          "totalCompletedTrainings": {
            "type": "integer"
          }
        }
      },
      "SignUpRequest": {
        "type": "object",
        "required": [
          "name",
          "email",
          "password"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "User name",
            "example": "UserName"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "mail@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "example": "abcdef1"
          }
        }
      },
      "SignUpResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "mail@gmail.com"
          },
          "name": {
            "type": "string",
            "description": "User name",
            "example": "UserName"
          },
          "bodyData": {
            "type": "object",
            "description": "User body data",
            "example": null
          },
          "token": {
            "type": "string",
            "description": "User token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTYxNzUyYTMzZGYxNzNhOTk1Mzc2YyIsImlhdCI6MTY5MzIxOTQ4NSwiZXhwIjoxNjkzMzAyMjg1fQ.IsTt6p3jiZxutBpEkiz7i4IgKpgVISUMH5VZksS0V50"
          }
        },
        "example": {
          "email": "mail@gmail.com",
          "name": "UserName",
          "bodyData": null,
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTYxNzUyYTMzZGYxNzNhOTk1Mzc2YyIsImlhdCI6MTY5MzIxOTQ4NSwiZXhwIjoxNjkzMzAyMjg1fQ.IsTt6p3jiZxutBpEkiz7i4IgKpgVISUMH5VZksS0V50"
        }
      },
      "SignInRequest": {
        "type": "object",
        "required": [
          "email",
          "password"
        ],
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "mail@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "example": "abcdef1"
          }
        }
      },
      "SignInResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "mail@gmail.com"
          },
          "name": {
            "type": "string",
            "description": "User name",
            "example": "UserName"
          },
          "bodyData": {
            "type": "object",
            "description": "User body data",
            "example": [
              null,
              {
                "height": 169,
                "currentWeight": 145,
                "desiredWeight": 129,
                "birthday": "1971-02-12T23:00:00.000Z",
                "blood": 1,
                "sex": "male",
                "levelActivity": 3,
                "dailyRateCalories": 799,
                "dailySportMin": 20
              }
            ]
          },
          "token": {
            "type": "string",
            "description": "User token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTYxNzUyYTMzZGYxNzNhOTk1Mzc2YyIsImlhdCI6MTY5MzIxOTQ4NSwiZXhwIjoxNjkzMzAyMjg1fQ.IsTt6p3jiZxutBpEkiz7i4IgKpgVISUMH5VZksS0V50"
          }
        },
        "example": {
          "email": "mail@gmail.com",
          "name": "UserName",
          "bodyData": {
            "height": 169,
                "currentWeight": 145,
                "desiredWeight": 129,
                "birthday": "1971-02-12T23:00:00.000Z",
                "blood": 1,
                "sex": "male",
                "levelActivity": 3,
                "dailyRateCalories": 799,
                "dailySportMin": 20
          },
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTYxNzUyYTMzZGYxNzNhOTk1Mzc2YyIsImlhdCI6MTY5MzIxOTQ4NSwiZXhwIjoxNjkzMzAyMjg1fQ.IsTt6p3jiZxutBpEkiz7i4IgKpgVISUMH5VZksS0V50"
        }
      },
      "GetCurrentResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User id",
            "example": "64e61752a33df173a995376c"
          },
          "name": {
            "type": "string",
            "description": "User name",
            "example": "UserName"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "mail@gmail.com"
          },
          "token": {
            "type": "string",
            "description": "User token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTYxNzUyYTMzZGYxNzNhOTk1Mzc2YyIsImlhdCI6MTY5MzIxOTQ4NSwiZXhwIjoxNjkzMzAyMjg1fQ.IsTt6p3jiZxutBpEkiz7i4IgKpgVISUMH5VZksS0V50"
          },
          "avatar": {
            "type": "string",
            "description": "User avatar",
            "example": "https://res.cloudinary.com/dhgbndjlm/image/upload/v1693235748/avatars/kvn40yxqcamrcdhilafx.png"
            
          },
          "bodyData": {
            "type": "object",
            "description": "User body data",
            "example": [
              null,
              {
                "height": 169,
                "currentWeight": 145,
                "desiredWeight": 129,
                "birthday": "1971-02-12T23:00:00.000Z",
                "blood": 1,
                "sex": "male",
                "levelActivity": 3,
                "dailyRateCalories": 799,
                "dailySportMin": 20
              }
            ]
          }
        },
        "example": {
          "_id": "64b1e25f6b0a2ccb95591ec7",
          "name": "UserName",
          "email": "mail@gmail.com",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjFlMjVmNmIwYTJjY2I5NTU5MWVjNyIsImlhdCI6MTY4OTM3OTQyMywiZXhwIjoxNjg5NDYyMjIzfQ.hT2Ta6pBhDR1vOF7LjcKxofyASDPjcTZtFi9CESKIuA",
          "avatar": "https://res.cloudinary.com/dhgbndjlm/image/upload/v1693235748/avatars/kvn40yxqcamrcdhilafx.png",
          "bodyData": {
            "height": 169,
                "currentWeight": 145,
                "desiredWeight": 129,
                "birthday": "1971-02-12T23:00:00.000Z",
                "blood": 1,
                "sex": "male",
                "levelActivity": 3,
                "dailyRateCalories": 799,
                "dailySportMin": 20
          }
        }
      },
      "AddBodyRequest": {
        "type": "object",
        "required": [
          "height",
          "currentWeight",
          "desiredWeight",
          "birthday",
          "blood",
          "sex",
          "levelActivity"
        ],
        "properties": {
          "height": {
            "type": "number",
            "description": "User height",
            "example": 169
          },
          "currentWeight": {
            "type": "number",
            "description": "User's current weight",
            "example": 145
          },
          "desiredWeight": {
            "type": "number",
            "description": "User's desired weight",
            "example": 129
          },
          "birthday": {
            "type": "number",
            "description": "User's birthday",
            "format": "date",
            "example": "1971-02-12T23:00:00.000Z"
          },
          "blood": {
            "type": "integer",
            "enum": [
              1,
              2,
              3,
              4
            ],
            "description": "User's blood type",
            "example": 1
          },
          "sex": {
            "type": "string",
            "enum": [
              "male",
              "female"
            ],
            "description": "User's sex",
            "example": "male"
          },
          "levelActivity": {
            "type": "integer",
            "enum": [
              1,
              2,
              3,
              4
            ],
            "description": "User's level activity",
            "example": 3
          }
        }
      },
      "AddBodyResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User id",
            "example": "64b1e25f6b0a2ccb95591ec7"
          },
          "name": {
            "type": "string",
            "description": "User name",
            "example": "UserName"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "mail@gmail.com"
          },
          "token": {
            "type": "string",
            "description": "User token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjFlMjVmNmIwYTJjY2I5NTU5MWVjNyIsImlhdCI6MTY4OTM3OTQyMywiZXhwIjoxNjg5NDYyMjIzfQ.hT2Ta6pBhDR1vOF7LjcKxofyASDPjcTZtFi9CESKIuA"
          },
          "avatar": {
            "type": "string",
            "description": "User avatar",
            "example": "https://res.cloudinary.com/dhgbndjlm/image/upload/v1693235748/avatars/kvn40yxqcamrcdhilafx.png"
          },
          "bodyData": {
            "type": "object",
            "description": "User body data",
            "example": [
              null,
              {
                "height": 169,
                "currentWeight": 145,
                "desiredWeight": 129,
                "birthday": "1971-02-12T23:00:00.000Z",
                "blood": 1,
                "sex": "male",
                "levelActivity": 3,
                "dailyRateCalories": 799,
                "dailySportMin": 20
              }
            ]
          }
        },
        "example": {
          "_id": "64b1e25f6b0a2ccb95591ec7",
          "name": "UserName",
          "email": "mail@gmail.com",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjFlMjVmNmIwYTJjY2I5NTU5MWVjNyIsImlhdCI6MTY4OTM3OTQyMywiZXhwIjoxNjg5NDYyMjIzfQ.hT2Ta6pBhDR1vOF7LjcKxofyASDPjcTZtFi9CESKIuA",
          "avatar": "https://res.cloudinary.com/dhgbndjlm/image/upload/v1693235748/avatars/kvn40yxqcamrcdhilafx.png",
          "bodyData": {
            "height": 169,
                "currentWeight": 145,
                "desiredWeight": 129,
                "birthday": "1971-02-12T23:00:00.000Z",
                "blood": 1,
                "sex": "male",
                "levelActivity": 3,
                "dailyRateCalories": 799,
                "dailySportMin": 20
          }
        }
      },
      "UserUpdateRequest": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "User name",
            "example": "UserName"
          },
          "avatar": {
            "type": "string",
            "description": "User image",
            "example": "https://res.cloudinary.com/dhgbndjlm/image/upload/v1693235748/avatars/kvn40yxqcamrcdhilafx.png"
          }
        }
      },
      "UserUpdateResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User id",
            "example": "64b1e25f6b0a2ccb95591ec7"
          },
          "name": {
            "type": "string",
            "description": "User name",
            "example": "UserName"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "mail@gmail.com"
          },
          "token": {
            "type": "string",
            "description": "User token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjFlMjVmNmIwYTJjY2I5NTU5MWVjNyIsImlhdCI6MTY4OTM3OTQyMywiZXhwIjoxNjg5NDYyMjIzfQ.hT2Ta6pBhDR1vOF7LjcKxofyASDPjcTZtFi9CESKIuA"
          },
          "avatar": {
            "type": "string",
            "description": "User avatar",
            "example": "https://res.cloudinary.com/dhgbndjlm/image/upload/v1693235748/avatars/kvn40yxqcamrcdhilafx.png"
          },
          "bodyData": {
            "type": "object",
            "description": "User body data",
            "example": [
              null,
              {
                "height": 190,
                "currentWeight": 130,
                "desiredWeight": 109,
                "birthday": "1991-05-24T23:00:00.000Z",
                "blood": 3,
                "sex": "male",
                "levelActivity": 1,
                "dailyRateCalories": 2799,
                "dailySportMin": 110
              }
            ]
          }
        },
        "example": {
          "_id": "64b1e25f6b0a2ccb95591ec7",
          "name": "UserName",
          "email": "mail@gmail.com",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjFlMjVmNmIwYTJjY2I5NTU5MWVjNyIsImlhdCI6MTY4OTM3OTQyMywiZXhwIjoxNjg5NDYyMjIzfQ.hT2Ta6pBhDR1vOF7LjcKxofyASDPjcTZtFi9CESKIuA",
          "avatar": "https://res.cloudinary.com/dhgbndjlm/image/upload/v1693235748/avatars/kvn40yxqcamrcdhilafx.png",
          "bodyData": {
            "height": 190,
            "currentWeight": 130,
            "desiredWeight": 109,
            "birthday": "Mon May 24 1991 00:00:00 GMT+0100 GMT+0100",
            "blood": 3,
            "sex": "male",
            "levelActivity": 1,
            "dailyRateCalories": 2799,
            "dailySportMin": 110
          }
        }
      },      
      
      "SignOutResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Sign out success",
            "example": "Sign out success"
          }
        }       
      },
      "ProductsCategoryResponse": {
          "type": "object",
          "properties": {
            "message": {
              "type": "array",
              "description": "",
              "example": [
    "alcoholic drinks",
    "berries",
    "cereals",
    "dairy",
    "dried fruits",
    "eggs",
    "fish",
    "flour",
    "fruits",
    "meat",
    "mushrooms",
    "nuts",
    "oils and fats",
    "poppy",
    "sausage",
    "seeds",
    "sesame",
    "soft drinks",
    "vegetables and herbs"
]
            }
          }
          
        },
        "ProductsListResponse": {
          "type": "object",
          "properties": {
            "message": {
              "type": "object",
              "description": "Sign out success",
              "example": [
    {
        "_id": "5d51694902b2373622ff5ccf",
        "weight": 100,
        "calories": 110,
        "category": "dried fruits",
        "title": "Dried rosehip",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5c95",
        "weight": 100,
        "calories": 213,
        "category": "nuts",
        "title": "Canned chestnut",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694902b2373622ff5cb8",
        "weight": 100,
        "calories": 305,
        "category": "seeds",
        "title": "Dill seeds",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5e03",
        "weight": 100,
        "calories": 91,
        "category": "vegetables and herbs",
        "title": "Cocktail salad Bonduelle Hawaiian marinated",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5ef6",
        "weight": 100,
        "calories": 100,
        "category": "soft drinks",
        "title": "Coffee Maxwell House instant dry",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5bf2",
        "weight": 100,
        "calories": 50,
        "category": "fruits",
        "title": "Feronia (Wooden Apple)",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff57bd",
        "weight": 100,
        "calories": 327,
        "category": "dairy",
        "title": "Reblochon cheese",
        "groupBloodNotAllowed": {
            "1": true,
            "2": true,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff599e",
        "weight": 100,
        "calories": 240,
        "category": "meat",
        "title": "Chopped lamb cutlets",
        "groupBloodNotAllowed": {
            "1": false,
            "2": true,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694902b2373622ff5a46",
        "weight": 100,
        "calories": 31,
        "category": "berries",
        "title": "Blackberry 4 seasons",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694802b2373622ff55a5",
        "weight": 100,
        "calories": 364,
        "category": "cereals",
        "title": "Oatmeal Myllyn Paras Tropic Sugar",
        "groupBloodNotAllowed": {
            "1": true,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694802b2373622ff55ab",
        "weight": 100,
        "calories": 88,
        "category": "cereals",
        "title": "Oatmeal on the water",
        "groupBloodNotAllowed": {
            "1": true,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5779",
        "weight": 100,
        "calories": 265,
        "category": "dairy",
        "title": "Cheese Dor Blue a la creme",
        "groupBloodNotAllowed": {
            "1": true,
            "2": true,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b81",
        "weight": 100,
        "calories": 180,
        "category": "fish",
        "title": "Butter fish smoked",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5920",
        "weight": 100,
        "calories": 142,
        "category": "meat",
        "title": "Pork beef stroganoff",
        "groupBloodNotAllowed": {
            "1": false,
            "2": true,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694902b2373622ff5953",
        "weight": 100,
        "calories": 86,
        "category": "meat",
        "title": "beef kidneys",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b14",
        "weight": 100,
        "calories": 87,
        "category": "fish",
        "title": "Pike caviar",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b58",
        "weight": 100,
        "calories": 125,
        "category": "fish",
        "title": "red-eyed",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5e5b",
        "weight": 100,
        "calories": 24,
        "category": "vegetables and herbs",
        "title": "Green beans",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694802b2373622ff55bf",
        "weight": 100,
        "calories": 350,
        "category": "cereals",
        "title": "Oat flakes Myllyn Paras",
        "groupBloodNotAllowed": {
            "1": true,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b2b",
        "weight": 100,
        "calories": 138,
        "category": "fish",
        "title": "Canned carp",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    }
]
            }
          }
          
        },
        "ProductsListFilteredBloodResponse":{
          "type": "object",
          "properties": {
            "message": {
              "type": "object",
              "description": "Sign out success",
              "example": [
    {
        "_id": "5d51694902b2373622ff5ccf",
        "weight": 100,
        "calories": 110,
        "category": "dried fruits",
        "title": "Dried rosehip",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5c95",
        "weight": 100,
        "calories": 213,
        "category": "nuts",
        "title": "Canned chestnut",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694902b2373622ff5cb8",
        "weight": 100,
        "calories": 305,
        "category": "seeds",
        "title": "Dill seeds",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5e03",
        "weight": 100,
        "calories": 91,
        "category": "vegetables and herbs",
        "title": "Cocktail salad Bonduelle Hawaiian marinated",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5ef6",
        "weight": 100,
        "calories": 100,
        "category": "soft drinks",
        "title": "Coffee Maxwell House instant dry",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5bf2",
        "weight": 100,
        "calories": 50,
        "category": "fruits",
        "title": "Feronia (Wooden Apple)",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5a46",
        "weight": 100,
        "calories": 31,
        "category": "berries",
        "title": "Blackberry 4 seasons",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694802b2373622ff55a5",
        "weight": 100,
        "calories": 364,
        "category": "cereals",
        "title": "Oatmeal Myllyn Paras Tropic Sugar",
        "groupBloodNotAllowed": {
            "1": true,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694802b2373622ff55ab",
        "weight": 100,
        "calories": 88,
        "category": "cereals",
        "title": "Oatmeal on the water",
        "groupBloodNotAllowed": {
            "1": true,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b81",
        "weight": 100,
        "calories": 180,
        "category": "fish",
        "title": "Butter fish smoked",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5953",
        "weight": 100,
        "calories": 86,
        "category": "meat",
        "title": "beef kidneys",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b14",
        "weight": 100,
        "calories": 87,
        "category": "fish",
        "title": "Pike caviar",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b58",
        "weight": 100,
        "calories": 125,
        "category": "fish",
        "title": "red-eyed",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5e5b",
        "weight": 100,
        "calories": 24,
        "category": "vegetables and herbs",
        "title": "Green beans",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694802b2373622ff55bf",
        "weight": 100,
        "calories": 350,
        "category": "cereals",
        "title": "Oat flakes Myllyn Paras",
        "groupBloodNotAllowed": {
            "1": true,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b2b",
        "weight": 100,
        "calories": 138,
        "category": "fish",
        "title": "Canned carp",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5b9d",
        "weight": 100,
        "calories": 67,
        "category": "fruits",
        "title": "Apricot canned",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5d12",
        "weight": 100,
        "calories": 31,
        "category": "vegetables and herbs",
        "title": "Broccoli 4 seasons",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5bea",
        "weight": 100,
        "calories": 25,
        "category": "fruits",
        "title": "Syzygium",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    },
    {
        "_id": "5d51694902b2373622ff5a9a",
        "weight": 100,
        "calories": 274,
        "category": "sausage",
        "title": "Krovyanka",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": false
        }
    }
]
            }
          }
        },
        "ProductsListFilteredCategoryResponse":{
          "type": "object",
          "properties": {
            "message": {
              "type": "object",
              "description": "Sign out success",
              "example": [
    {
        "_id": "5d51694902b2373622ff5c95",
        "weight": 100,
        "calories": 213,
        "category": "nuts",
        "title": "Canned chestnut",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694902b2373622ff5cad",
        "weight": 100,
        "calories": 354,
        "category": "nuts",
        "title": "Seychelles Walnut Coco de Mer",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694902b2373622ff5c97",
        "weight": 100,
        "calories": 680,
        "category": "nuts",
        "title": "Pine nuts",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694902b2373622ff5c9c",
        "weight": 100,
        "calories": 354,
        "category": "nuts",
        "title": "Coconut",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    },
    {
        "_id": "5d51694902b2373622ff5c86",
        "weight": 100,
        "calories": 656,
        "category": "nuts",
        "title": "Brazilian nut",
        "groupBloodNotAllowed": {
            "1": false,
            "2": false,
            "3": false,
            "4": true
        }
    }
]
            }
          }
        }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
    
  }
}